### ISSUE TITLE
python sdk update memory bug

### ISSUE THREAD

**Issue by YZF-Myself** [mem0ai/mem0#1917] opened 2024-09-27 07:28 UTC
### 🐛 Describe the bug

    def update(self, memory_id, data):
        """
        Update a memory by ID.

        Args:
            memory_id (str): ID of the memory to update.
            data (dict): Data to update the memory with.

        Returns:
            dict: Updated memory.
        """
        capture_event("mem0.update", self, {"memory_id": memory_id})
        existing_embeddings = { data: self.embedding_model.embed(data) }  # add existing_embeddings 
        self._update_memory(memory_id, data, existing_embeddings)
        return {"message": "Memory updated successfully!"}

**Comment by YZF-Myself** [comment] 2024-09-27 07:29
def _update_memory(self, memory_id, data, existing_embeddings, metadata=None):

so, need add existing_embeddings in def update(self, memory_id, data)

**Comment by parshvadaftari** [comment] 2024-09-27 13:45
@YZF-Myself I have raised a PR for this issue.

**Comment by parshvadaftari** [comment] 2024-10-08 09:57
@YZF-Myself The issue is solved with the PR #1939 you can check out the latest commit.

**Comment by YZF-Myself** [comment] 2024-10-08 10:04
ok, I get it.

**Comment by Dev-Khant** [comment] 2024-10-15 11:19
Closing this issue as it has been fixed. Please feel free to open again if same problem occurs

**Closed by Dev-Khant** 2024-10-15 11:19 UTC
